# 2. Data Structures & Scientific Python

By the end of this session you should be able to:
- Store and manipulate collections of data
- Create NumPy arrays and understand the advantages they offer over Python lists
- Use NumPy to solve common mathematical problems
- Select the appropriate data structure for a given problem

## Core Data Structures

The 4 most common ways to store data in Python are:
1. Lists: ordered collection of data, mutable (we can change, add or remove items after the list has been created)
2. Tuples: ordered collection of data, immutable (we cannot change, add or remove items after the tuple has been created)
3. Dicts: collection of key-value pairs
4. Sets: unordered collection of unique items (duplicate values are automatically removed)

Let's start using lists:

In [1]:
my_list = [1, 2, 3, 4, 5]

To access an element in the list, we use its index. In Python indices always start at 0. You can also access indices from the end of the list.

| Element        | 1st | 2nd | ... | 2nd to last | Last |
|----------------|-----|-----|-----|-------------|------|
| Positive index | `0` | `1` | ... | `n-2`       | `n-1`|
| Negative index | `-n`| `-(n-1)` | ... | `-2`   | `-1` |

Here `n` is the length of the list.

In [2]:
print(len(my_list))

5


In [3]:
print(my_list[0])
print(my_list[-2])

1
4


To access multiple elements of a list, we can use slicing, defined using `:`. The number before the colon is the starting index (default `0`), and the number after is the ending index, which is exclusive (default is the end of the list). For example:

In [4]:
print(my_list)
print(my_list[1:3])  # elements at index 1 and 2
print(my_list[:3])   # from the start up to index 2
print(my_list[2:])   # from index 2 to the end
print(my_list[:])    # the entire list

[1, 2, 3, 4, 5]
[2, 3]
[1, 2, 3]
[3, 4, 5]
[1, 2, 3, 4, 5]


Lists can also contain elements of different types.

In [5]:
my_list[1] = 100
my_list[2] = 'hello'
print(my_list)

[1, 100, 'hello', 4, 5]


In [6]:
my_list[5] = 3

IndexError: list assignment index out of range

Methods are functions that belong to a specific object and are called using dot notation: `my_list.append(3)`. Lists have several built-in methods for common operations.
- `append(x)`: adds an element to the end
- `pop(i)`: removes and returns an element by index (defaults to last)
- `sort()`: sorts the list in place

In [8]:
my_list.pop(2)

'hello'

In [9]:
print(my_list)

[1, 100, 4, 5]


As well as methods, Python provides several built-in functions that are useful for working with lists:

In [10]:
print(len(my_list))       # number of elements
print(sum(my_list))       # sum of all elements
print(min(my_list))       # smallest element
print(max(my_list))       # largest element
print(sorted(my_list))    # returns a new sorted list

4
110
1
100
[1, 4, 5, 100]


If we try to do similar operations with tuples, we will get an error:

In [11]:
my_tuple = (1, 2, 3)
my_tuple[0] = 10

TypeError: 'tuple' object does not support item assignment

In [13]:
# dictionaries
person = {"name": "Alice", "age": 25}
print(person["name"])
person["profession"] = "teacher"

Alice


In [14]:
print(person["Bob"])

KeyError: 'Bob'

You can also iterate through the keys in a dictionary using `.keys`:

In [17]:
for key in person.keys():
    print(f"Key: {key}, Value: {person[key]}")

Key: name, Value: Alice
Key: age, Value: 25
Key: profession, Value: teacher


In [18]:
# sets
fruits = {"apple", "banana", "apple"}
print(fruits)  # duplicates removed

{'apple', 'banana'}


## NumPy

In Python, you use the `import` keyword to make code in one module available in another. You may want to import your own code, for example a library of functions you want to access (without re-defining everything), or a class (an object-contructor script). This is really helpful for organizing your code.

You can also import modules and packages available online (after download and installation). Each module/package has online documentation explaining the usage of each function/class.

NumPy is one of the most commonly used packages in Python. The documentation can be found in https://numpy.org/devdocs/index.html. Let's begin by importing the package!

In [19]:
import numpy as np

Python lists are flexible, but they were not designed for numerical computation. Consider adding two vectors:

In [20]:
a = [1, 2, 3]
b = [4, 5, 6]
a + b

[1, 2, 3, 4, 5, 6]

NumPy arrays behave the way we expect:

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

A NumPy array has three key properties: `dtype` (the data type of its elements - all elements must have the same data type!), `shape` (its dimensions as a tuple), and `ndim` (the number of dimensions).

In [22]:
matrix = np.array([[1, 3, 5], [2, 4, 6]])

print(matrix.dtype)
print(matrix.shape)
print(matrix.ndim)

int64
(2, 3)
2


There are different ways of creating arrays.

In [23]:
# arrays of zeros and ones
print(np.zeros(5))
print(np.ones((2, 3))) # 2 rows, 3 columns

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# evenly spaced values
print(np.arange(10))
print(np.arange(start=0, stop=10, step=2))
dt = 0.1
print(np.arange(start=2, stop=10, step=dt))

# if you want to specify the number of equally-spaced values between start & stop:
print(np.linspace(start=0, stop=1, num=5))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7
 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5
 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3
 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1
 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[0.   0.25 0.5  0.75 1.  ]


NumPy arrays support the same slicing syntax as Python lists, and extend it naturally to multiple dimensions: `a[0, :]` selects the first row, `a[:, 1]` selects the second column.

### Vector operations

Arithmetic operators (`+`, `-`, `*`, `/`, `**`) apply element-wise to NumPy arrays. NumPy also provides additional mathematical functions via `np.`, such as `np.sqrt()`, `np.sin()`, and `np.dot()`. For a full list, see the NumPy function reference.


In [25]:
a = np.array([1, 4, 9])
b = np.array([2, 3, 4])

print(a + b)
print(a * 2)
print(np.sqrt(a))
print(np.dot(a, b))

[ 3  7 13]
[ 2  8 18]
[1. 2. 3.]
50


### Concatenation

At times you may still want to combine or concatenate vectors. You can do this through `np.concatenate`. By default, concatenation occurs acros the first dimension (`0`), but you can also specify the dimension.

In [26]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print(np.concatenate([a, b]))
print(np.concatenate([a, b], axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


For concatenating along the `0` and `1` dimension, you can simply use `np.vstack` and `np.hstack`.

In [27]:
print(np.vstack([a, b]))
print(np.hstack([a, b]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Broadcasting

When an operation involves arrays of different shapes, NumPy automatically expands the smaller array to match. This is called broadcasting.

In [28]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a + 10        # adds 10 to every element

array([[11, 12, 13],
       [14, 15, 16]])

Note that dimensions must be compatible for broadcasting to work.

In [29]:
a + np.arange(4)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

### Linear Algebra

NumPy provides tools for the most common linear algebra operations you will encounter. A common point of confusion is the difference between element-wise multiplication and matrix multiplication. By default, arithmetic operators act element-wise. To perform matrix multiplication, use the `@` operator:

In [30]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A * B)
print(A @ B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


We can use `np.linalg` to perform matrix operations such as computing the inverse, determinant or the eigenvelues and eigenvectors of a matrix.

In [31]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [32]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [33]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132+0.j,  5.37228132+0.j]), eigenvectors=array([[-0.82456484+0.j, -0.41597356+0.j],
       [ 0.56576746+0.j, -0.90937671+0.j]]))

To solve a linear system of the form $Ax = b$, we can compute $x = A^{-1}b$.

In [34]:
x =  np.linalg.inv(A) @ b
print(x)

[[-3. -4.]
 [ 4.  5.]]


However, `np.linalg.solve` is preferred over computing the inverse explicitly because it is faster and more stable numerically.

In [35]:
x_solve = np.linalg.solve(A, b)
print(x_solve)

[[-3. -4.]
 [ 4.  5.]]


We can also compute the norm of a vector using `np.linalg.norm`.

In [36]:
print(np.linalg.norm(A@x - b))
print(np.linalg.norm(A@x_solve - b))

1.7763568394002505e-15
0.0


The residual is not zero because of floating point arithmetic. Computers cannot represent real numbers exactly, so small rounding errors accumulate. This value is effectively zero.

### Random numbers

We can also use NumPy to sample from a range of distributions. Here are a few examples:

In [37]:
A = np.random.uniform(size=(3,3)) # you can specify the range here with low= and high=
b = np.random.rand(3) # range is by default [0, 1]
print(A)
print(b)

[[0.93210379 0.57212321 0.34961898]
 [0.27141957 0.22441335 0.10623126]
 [0.21154334 0.54246883 0.63559848]]
[0.75716381 0.67956346 0.59111039]


Let's compute some statistics:

In [38]:
print("Mean:", A.mean())
print("Variance:", A.var())
print("Standard Deviation:", A.std())

Mean: 0.4272800896296467
Variance: 0.06150942804158811
Standard Deviation: 0.24801094339078691


For more advanced mathematical operations (integration, solving differential equations, optimisation) the SciPy library builds directly on NumPy and is worth exploring. See the SciPy documentation https://docs.scipy.org/doc/scipy/ for a full overview.

## Exercises

1. Create a list of the first 10 positive integers. Using slicing, extract (i) the first 5 elements, (ii) the even elements, (iii) the last 3 elements.

In [39]:
numbers = list(range(1, 11))

first_five = numbers[:5]
even = numbers[1::2]
last_three = numbers[-3:]

print(first_five, even, last_three)

[1, 2, 3, 4, 5] [2, 4, 6, 8, 10] [8, 9, 10]


2. Given the two lists below, use a set to find (i) the unique elements across both lists, (ii) the elements that appear in both lists.

In [40]:
a = [1, 2, 2, 3, 4, 4, 5]
b = [3, 4, 5, 5, 6, 7]

In [41]:
unique = set(a + b)
common = set(a) & set(b)

In [42]:
# alternatively you can compute the common elements using the following:
common = set()
for x in a:
    if x in b:
        common.add(x)

3. Generate a $3 \times 3$ random matrix whose entries are sampled from a standard normal distribution and compute their mean and variance.

In [43]:
A = np.random.randn(3, 3)

print("Mean:", np.mean(A))
print("Variance:", np.var(A))

Mean: -0.19030417184273796
Variance: 0.9278346169299394


4. Write a function that takes as input a matrix $A$ and vector $b$ and solves the linear system $Ax=b$.

In [44]:
def solve_linear_system(A, b):
    """Solve the linear system Ax = b and return the solution vector x"""
    x = np.linalg.solve(A, b)
    return x

5. Use the matrix from Q3 and the function from Q4 to solve the system $Ax = b$ for $b=(1, 2, 3)$. Verify that your answer is correct by computing the residual.

In [45]:
b = np.array([1, 2, 3])
x = solve_linear_system(A, b)

print("Solution x =", x)
print("Residual =", np.linalg.norm(A @ x - b))

Solution x = [ 9.15837477 -2.1106803  -7.63903735]
Residual = 2.5510982866352577e-15


6. The code below measures how long it takes to compute the sum of 10 million numbers using a Python list. Using it as a template, write the equivalent using a NumPy array and compare the two runtimes.

In [46]:
import time

n = 10_000_000

# Python list
data_list = list(range(n))
start = time.time()
total = sum(data_list)
print("List time:", time.time() - start, "seconds")

# Your NumPy version here
data_array = np.arange(n)
start = time.time()
total = np.sum(data_array)
print("NumPy time:", time.time() - start, "seconds")

List time: 0.13553214073181152 seconds
NumPy time: 0.008966922760009766 seconds
